### GET RIDER COORDINATES
GET http://localhost:3000/riders/coordinates/1

### POST RIDER COORDINATES
POST http://localhost:3000/riders/coordinates
Content-Type: application/json

{
    "lat": 3333.23,
    "lng": 333333.23,
    "rider": 1
}

### CREATE RIDER
POST http://localhost:3000/riders
Content-Type: application/json

{
    "firstName": "Polaa",
    "lastName": "Smith",
    "email" : "plat@gmail.com"

}


### API GATEWAY
GET http://localhost:3000/riders/2

### AUTH ROUTES

### Signup
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "new_user13642@gmail.com",
    "password": "123123adasd"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "new_user13642@gmail.com",
    "password": "123123adasd"
}



### Profile
POST http://localhost:3000/auth/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImVtYWlsIjoibmV3X3VzZXIxMzY0MkBnbWFpbC5jb20iLCJpYXQiOjE3NDI1MDkzNjIsImV4cCI6MTc0MjUxMjk2Mn0.MW23PcOejKEUUhO27vQE8K2TWKjUhX9iviANxwwzh8M