### GET RIDER COORDINATES
GET http://localhost:3002/rider-coordinates/1

### POST RIDER COORDINATES
POST http://localhost:3002/rider-coordinates
Content-Type: application/json

{
    "lat": 5555.23,
    "lng": 4444434.23,
    "rider": 1
}

### CREATE RIDER
POST http://localhost:3003/rider
Content-Type: application/json

{
    "firstName": "Jane",
    "lastName": "Doe",
    "email" : "jane@gmail.com"

}