### GET RIDER COORDINATES
GET http://localhost:3000/riders/coordinates/1

### POST RIDER COORDINATES
POST http://localhost:3000/riders/coordinates
Content-Type: application/json

{
    "lat": 3333.23,
    "lng": 333333.23,
    "rider": 1
}

### CREATE RIDER
POST http://localhost:3000/riders
Content-Type: application/json

{
    "firstName": "Polaa",
    "lastName": "Smith",
    "email" : "plat@gmail.com"

}


### API GATEWAY
GET http://localhost:3000/riders/2
